// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emqwycnzvrejoultbulb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcXd5Y256dnJlam91bHRidWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDIxMzksImV4cCI6MjA2NDcxODEzOX0.YTHf3gg_qZ9rA7ejJjrulbtB01IetVxtCG8LYTQ3BFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);